CREATE TABLE [dbo].[RECONSILEDDATA] (
    [ID]          INT             IDENTITY (1, 1) NOT NULL,
    [RRN]         NVARCHAR (MAX)  NOT NULL,
    [DATE]        DATE            NOT NULL,
    [AMOUNT]      NUMERIC (18, 2) NULL,
    [RECOCOL4]    NVARCHAR (MAX)  DEFAULT ('NA') NOT NULL,
    [RECOCOL5]    NVARCHAR (MAX)  DEFAULT ('NA') NOT NULL,
    [RECOCOL6]    NVARCHAR (MAX)  DEFAULT ('NA') NOT NULL,
    [RECOCOL7]    NVARCHAR (MAX)  DEFAULT ('NA') NOT NULL,
    [RECOCOL8]    NVARCHAR (MAX)  DEFAULT ('NA') NOT NULL,
    [RECOCOL9]    NVARCHAR (MAX)  DEFAULT ('NA') NOT NULL,
    [RECOCOL10]   NVARCHAR (MAX)  DEFAULT ('NA') NOT NULL,
    [RECOCOL11]   NVARCHAR (MAX)  DEFAULT ('NA') NOT NULL,
    [RECOCOL12]   NVARCHAR (MAX)  DEFAULT ('NA') NOT NULL,
    [RECOCOL13]   NVARCHAR (MAX)  DEFAULT ('NA') NOT NULL,
    [RECOCOL14]   NVARCHAR (MAX)  DEFAULT ('NA') NOT NULL,
    [RECOCOL15]   NVARCHAR (MAX)  DEFAULT ('NA') NOT NULL,
    [RECOCOL16]   NVARCHAR (MAX)  DEFAULT ('NA') NOT NULL,
    [TEMPLATEID]  INT             NOT NULL,
    [LASTUPDATE]  DATETIME2 (7)   DEFAULT (getdate()) NULL,
    [CREATEDDATE] DATETIME2 (7)   DEFAULT (getdate()) NULL
);


GO


create TRIGGER [dbo].[UPDATERECONSILERAWDATA]
ON [dbo].[RECONSILEDDATA]
AFTER UPDATE, INSERT, DELETE
AS


--IF EXISTS(SELECT * FROM INSERTED) AND EXISTS (SELECT * FROM DELETED)
--BEGIN
--	UPDATE DBO.[RECONSILERAWDATA] SET DATE = REPLACE(CONVERT(CHAR(10), getdate(), 103), '/', '')
--	FROM INSERTED I
--	WHERE DBO.[RECONSILERAWDATA].ID = I.ID and I.DATE = '' or I.DATE IS NULL
--END

IF EXISTS (SELECT * FROM INSERTED) AND NOT EXISTS(SELECT * FROM DELETED)
BEGIN
    UPDATE DBO.[RECONSILERAWDATA] SET ISRECONSILED = 1
	FROM INSERTED I
	WHERE DBO.[RECONSILERAWDATA].RRN = I.RRN 
	and DBO.[RECONSILERAWDATA].DATE  = I.DATE 
	AND DBO.[RECONSILERAWDATA].AMOUNT  = I.AMOUNT
	AND DBO.[RECONSILERAWDATA].[RECOCOL4] 	 = I.RECOCOL4
	AND DBO.[RECONSILERAWDATA].[RECOCOL5] 	 = I.RECOCOL5
	AND DBO.[RECONSILERAWDATA].[RECOCOL6] 	 = I.RECOCOL6
	AND DBO.[RECONSILERAWDATA].[RECOCOL7] 	 = I.RECOCOL7
    AND DBO.[RECONSILERAWDATA].[RECOCOL8] 	 = I.RECOCOL8
	AND DBO.[RECONSILERAWDATA].[RECOCOL9] 	 = I.RECOCOL9
	AND DBO.[RECONSILERAWDATA].[RECOCOL10]	 = I.RECOCOL10
	AND DBO.[RECONSILERAWDATA].[RECOCOL11]	 = I.RECOCOL11
	AND DBO.[RECONSILERAWDATA].[RECOCOL12]	 = I.RECOCOL12
	AND DBO.[RECONSILERAWDATA].[RECOCOL13]	 = I.RECOCOL13
	AND DBO.[RECONSILERAWDATA].[RECOCOL14]	 = I.RECOCOL14
	AND DBO.[RECONSILERAWDATA].[RECOCOL15]	 = I.RECOCOL15
	AND DBO.[RECONSILERAWDATA].[RECOCOL16]	 = I.RECOCOL16	
	
	UPDATE DBO.[PRIMARYRECONSILEDATA] SET ISRECONSILED = 1
	FROM INSERTED I
	WHERE DBO.[PRIMARYRECONSILEDATA].RRN = I.RRN 
	and DBO.[PRIMARYRECONSILEDATA].DATE  = I.DATE 
	AND DBO.[PRIMARYRECONSILEDATA].AMOUNT  = I.AMOUNT
	AND DBO.[PRIMARYRECONSILEDATA].[RECOCOL4] 	 = I.RECOCOL4
	AND DBO.[PRIMARYRECONSILEDATA].[RECOCOL5] 	 = I.RECOCOL5
	AND DBO.[PRIMARYRECONSILEDATA].[RECOCOL6] 	 = I.RECOCOL6
	AND DBO.[PRIMARYRECONSILEDATA].[RECOCOL7] 	 = I.RECOCOL7
    AND DBO.[PRIMARYRECONSILEDATA].[RECOCOL8] 	 = I.RECOCOL8
	AND DBO.[PRIMARYRECONSILEDATA].[RECOCOL9] 	 = I.RECOCOL9
	AND DBO.[PRIMARYRECONSILEDATA].[RECOCOL10]	 = I.RECOCOL10
	AND DBO.[PRIMARYRECONSILEDATA].[RECOCOL11]	 = I.RECOCOL11
	AND DBO.[PRIMARYRECONSILEDATA].[RECOCOL12]	 = I.RECOCOL12
	AND DBO.[PRIMARYRECONSILEDATA].[RECOCOL13]	 = I.RECOCOL13
	AND DBO.[PRIMARYRECONSILEDATA].[RECOCOL14]	 = I.RECOCOL14
	AND DBO.[PRIMARYRECONSILEDATA].[RECOCOL15]	 = I.RECOCOL15
	AND DBO.[PRIMARYRECONSILEDATA].[RECOCOL16]	 = I.RECOCOL16	
END	

