CREATE TABLE [dbo].[Template_Group] (
    [TemplateGroup_Id]    INT           IDENTITY (1, 1) NOT NULL,
    [Template_Group_Name] VARCHAR (400) NULL,
    [Is_Active]           BIT           CONSTRAINT [DF_Template_Group_Is_Active] DEFAULT ((0)) NULL,
    [LastUpdate]          DATETIME2 (7) NULL,
    [CreatedDate]         DATETIME2 (7) NULL
);


GO


CREATE TRIGGER [dbo].[UPDATETemplate_Group]
ON [dbo].[Template_Group]
AFTER UPDATE, INSERT, DELETE
AS


IF EXISTS(SELECT * FROM INSERTED) AND EXISTS (SELECT * FROM DELETED)
BEGIN
	UPDATE DBO.[TEMPLATE_GROUP] SET LASTUPDATE=GETDATE() 
	FROM INSERTED I
	WHERE DBO.[TEMPLATE_GROUP].TEMPLATEGROUP_ID = I.TEMPLATEGROUP_ID

	UPDATE RECONSILE_TEMPLATE  SET TEMPLATE_GROUP_STATUS = I.IS_ACTIVE
	from INSERTED I WHERE RECONSILE_TEMPLATE.TEMPLATE_GROUP_ID = I.TEMPLATEGROUP_ID
END

IF EXISTS (SELECT * FROM INSERTED) AND NOT EXISTS(SELECT * FROM DELETED)
BEGIN
    UPDATE DBO.[TEMPLATE_GROUP] SET CREATEDDATE =GETDATE() 
	FROM INSERTED I
	WHERE DBO.[TEMPLATE_GROUP].TEMPLATEGROUP_ID = I.TEMPLATEGROUP_ID
END

