-- Batch submitted through debugger: SQLQuery4.sql|0|0|C:\Users\ramra\AppData\Local\Temp\~vs5FB1.sql
--EXEC P_GETDASHBOARDDATA 
CREATE PROCEDURE [DBO].[P_GetDashboardData]   
@GROUPTEMPLATEID INT=0    
AS    
BEGIN      
WITH DASHBOARDRESULT AS (  
SELECT RT.TEMPLATE_GROUP_ID AS GROUP_ID,SUM(AMOUNT) AS CONSILED_AMOUNT, NULL AS NON_CONSILED_AMOUNT,NULL AS PRIMARY_AMOUNT FROM RECONSILEDDATA RD  
JOIN RECONSILE_TEMPLATE RT ON RD.TEMPLATEID =RT.RECONSILE_TEMPLATE_ID  
WHERE RD.LASTUPDATE >= CAST(GETDATE() AS DATE) AND RD.TEMPLATEID IN (SELECT TEMPLATEID FROM TEMPLATE_GROUP WHERE IS_ACTIVE = 1)  
GROUP BY TEMPLATE_GROUP_ID   
UNION  
SELECT RT.TEMPLATE_GROUP_ID AS GROUP_ID,NULL AS CONSILED_AMOUNT, SUM(AMOUNT) AS NON_CONSILED_AMOUNT,NULL AS PRIMARY_AMOUNT FROM RECONSILERAWDATA RRD  
JOIN RECONSILE_TEMPLATE RT ON RRD.TEMPLATEID =RT.RECONSILE_TEMPLATE_ID  
WHERE RRD.LASTUPDATE >= CAST(GETDATE() AS DATE) AND ISRECONSILED = 0 AND TEMPLATEID IN (SELECT TEMPLATEID FROM TEMPLATE_GROUP WHERE IS_ACTIVE = 1)  
GROUP BY TEMPLATE_GROUP_ID   
UNION  
SELECT RT.TEMPLATE_GROUP_ID AS GROUP_ID,NULL AS CONSILED_AMOUNT, NULL AS NON_CONSILED_AMOUNT,SUM(AMOUNT) AS PRIMARY_AMOUNT FROM PRIMARYRECONSILEDATA RRD  
JOIN RECONSILE_TEMPLATE RT ON RRD.TEMPLATEID =RT.RECONSILE_TEMPLATE_ID  
WHERE RRD.LASTUPDATE >= CAST(GETDATE() AS DATE) AND ISRECONSILED = 0 AND TEMPLATEID IN (SELECT TEMPLATEID FROM TEMPLATE_GROUP WHERE IS_ACTIVE = 1)  
GROUP BY TEMPLATE_GROUP_ID  
)  
SELECT  TEMPLATEGROUP_ID  AS TemplateGroupId,SUM(CONSILED_AMOUNT) AS ConsiledAmount,SUM(NON_CONSILED_AMOUNT) AS NonConsiledAmount,SUM(PRIMARY_AMOUNT) AS PrimaryAmount,TG.TEMPLATE_GROUP_NAME AS TemplateGroupName FROM DASHBOARDRESULT DR  
RIGHT JOIN TEMPLATE_GROUP TG ON DR.GROUP_ID = TG.TEMPLATEGROUP_ID   
WHERE TG.IS_ACTIVE = 1  
GROUP BY TEMPLATEGROUP_ID,TEMPLATE_GROUP_NAME  
ORDER BY TEMPLATE_GROUP_NAME  
END 
