

--EXEC P_GetReconsileReportData 0,'Aug 10 2018','Aug 13 2018'  --used reconsile Process    
CREATE  PROCEDURE [dbo].[P_GetReconsileReportData]        
@GROUPTEMPLATEID INT=0,  
@ReconsileTypeId int =0, 
@FROMDATE DATETIME,    
@TODATE DATETIME      
AS          
BEGIN          
    
CREATE TABLE #RECONSILE_TEMPLATE     
(      
    TEMPLATE_ID INT    
)      
    
INSERT INTO #RECONSILE_TEMPLATE    
SELECT RECONSILE_TEMPLATE_ID FROM RECONSILE_TEMPLATE WHERE TEMPLATE_GROUP_ID = @GROUPTEMPLATEID  OR  (ISNULL(@GROUPTEMPLATEID, 0) = 0)    AND IS_ACTIVE =1    
    
  
    
SELECT RD.RRN PrimaryRRNNumber,  
RD.AMOUNT PrimaryAmount,  
CAST(RD.[DATE] AS DATE) AS [PrimaryDATE],  
RD.TEMPLATEID PrimaryTemplateId,   
RTT.TEMPLATE_NAME PrimaryTemplateName,   
CAST('TRUE' AS BIT) PrimaryIsReconsile,  
RD.RECONSILETYPE PrimaryReconsileType,  
RD.RECONSILEDESC PrimaryReconsileDesc,  
RRD.RRN NonPrimaryRRNNumber,  
RRD.AMOUNT NonPrimaryAmount,  
CAST(RRD.[DATE] AS DATE) AS [NonPrimaryDATE],  
RRD.TEMPLATEID NonPrimaryTemplateId,   
NRTT.TEMPLATE_NAME NonPrimaryTemplateName,   
CAST('TRUE' AS BIT) NonPrimaryIsReconsile,  
RRD.RECONSILETYPE NonPrimaryReconsileType,  
RRD.RECONSILEDESC NonPrimaryReconsileDesc,  
dense_Rank() OVER (ORDER BY RRD.TEMPLATEID ASC) denseCount  
  
FROM PRIMARYRECONSILEDATA RD   
join RECONSILERAWDATA RRD on RRD.PRIMARYID = RD.ID   
JOIN #RECONSILE_TEMPLATE RT ON RD.TEMPLATEID = RT.TEMPLATE_ID    
JOIN RECONSILE_TEMPLATE RTT ON RD.TEMPLATEID = RTT.RECONSILE_TEMPLATE_ID    
JOIN RECONSILE_TEMPLATE NRTT ON RRD.TEMPLATEID = NRTT.RECONSILE_TEMPLATE_ID    
WHERE CAST(RRD.LASTUPDATE AS DATE) BETWEEN @FROMDATE AND @TODATE   
AND (@ReconsileTypeId = 0 AND RRD.RECONSILETYPE ='A')
OR (@ReconsileTypeId = 1 AND RRD.RECONSILETYPE ='M')
OR (@ReconsileTypeId = 2 AND RRD.RECONSILETYPE IN ('A','M'))
END