-- Batch submitted through debugger: SQLQuery4.sql|0|0|C:\Users\ramra\AppData\Local\Temp\~vs5FB1.sql
--EXEC P_GETDASHBOARDDATA 
CREATE PROCEDURE [DBO].[P_GetDashboardData]   
@GROUPTEMPLATEID INT=0    
AS
BEGIN   
DECLARE  
@TEMPLATEID INT,     
@TEMPLATEGROUPID INT, 
@NUMBEROFBLANKROWS INT,
@PRIMARYTEMPLATEID INT, 
@TEMPALTEGROUPNAME VARCHAR(100),      
@TEMPALTENAME VARCHAR(100),        
@CONDITIONQUERY VARCHAR(MAX) ,
@@SQLQUERY VARCHAR(MAX),  
@@COUNT INT = 0,
@MAXTEMPLATECOUNT INT =(
SELECT MAX(Y.NUMBEROFTEMPLATE)
FROM(
SELECT DISTINCT TEMPLATEGROUP_ID,COUNT(RECONSILE_TEMPLATE_ID) AS NUMBEROFTEMPLATE
FROM RECONSILE_TEMPLATE RT
JOIN TEMPLATE_GROUP TG ON RT.TEMPLATE_GROUP_ID =TG.TEMPLATEGROUP_ID  AND  TG.IS_ACTIVE =1 
WHERE RT.IS_ACTIVE = 1  AND RT.ISPRIMARY = 0  
GROUP BY TEMPLATEGROUP_ID)Y) 




SET @@SQLQUERY = 'CREATE TABLE ##TEMPREMAININGCOUNT(TemplateGroupId int,NUMBEROFBLANKROWS int)'        
EXEC(@@SQLQUERY) 

INSERT INTO   ##TEMPREMAININGCOUNT   
SELECT DISTINCT TEMPLATEGROUP_ID,@maxTemplateCount - count(RECONSILE_TEMPLATE_ID) as NUMBEROFBLANKROWS
FROM RECONSILE_TEMPLATE RT
JOIN TEMPLATE_GROUP TG ON RT.TEMPLATE_GROUP_ID =TG.TEMPLATEGROUP_ID  AND  TG.IS_ACTIVE =1 
WHERE RT.IS_ACTIVE = 1  AND RT.IsPrimary = 0  
group by TEMPLATEGROUP_ID



SET @@SQLQUERY = ''
SET @@SQLQUERY = 'CREATE TABLE ##TEMPDASHBOARD(TemplateGroupId int,ConsiledAmount NUMERIC(18,2),NonConsiledAmount NUMERIC(18,2),TemplateGroupName  VARCHAR(400),[TemplateId] int,[TemplateName] VARCHAR(400))'        
EXEC(@@SQLQUERY)      

DECLARE RECONSILEREPORT_CURSOR CURSOR          
LOCAL  FORWARD_ONLY  FOR          
SELECT DISTINCT TEMPLATEGROUP_ID,TEMPLATE_GROUP_NAME, RECONSILE_TEMPLATE_ID,TEMPLATE_NAME,ISNULL(CONDITIONQUERY,'') AS CONDITIONQUERY,
ISNULL((SELECT RECONSILE_TEMPLATE_ID FROM RECONSILE_TEMPLATE WHERE TEMPLATE_GROUP_ID = TG.TEMPLATEGROUP_ID AND ISPRIMARY =1),0) AS PRIMARYTEMPLATEID       
FROM RECONSILE_TEMPLATE RT
JOIN TEMPLATE_GROUP TG ON RT.TEMPLATE_GROUP_ID =TG.TEMPLATEGROUP_ID  AND  TG.IS_ACTIVE =1 
WHERE RT.IS_ACTIVE = 1  AND RT.IsPrimary = 0         
OPEN RECONSILEREPORT_CURSOR          
FETCH NEXT FROM RECONSILEREPORT_CURSOR INTO  @TEMPLATEGROUPID,@TEMPALTEGROUPNAME,@TEMPLATEID,@TEMPALTENAME,@CONDITIONQUERY,@PRIMARYTEMPLATEID        
WHILE @@FETCH_STATUS = 0          
BEGIN       
		IF @@COUNT = 0         
		BEGIN 
			SET @@SQLQUERY = 'INSERT INTO ##TEMPDASHBOARD '   
		END
		ELSE
		BEGIN 
			SET @@SQLQUERY = @@SQLQUERY +' UNION ALL '  
		END

		SET @@SQLQUERY = @@SQLQUERY +' SELECT '+CAST(@TEMPLATEGROUPID AS VARCHAR(10)) +'   TemplateGroupId,SUM(AMOUNT) AS ConsiledAmount,NULL AS NonConsiledAmount,'''+ @TEMPALTEGROUPNAME +''' TemplateGroupName,'+CAST(@TEMPLATEID AS VARCHAR(10)) +'   TemplateId,'''+ @TEMPALTENAME +''' TemplateName 
		FROM RECONSILERAWDATA WHERE ISRECONSILED = 1  AND TEMPLATEID = '+CAST(@TEMPLATEID AS VARCHAR(10)) +' And CAST(LASTUPDATE AS DATE) >= ''' + CAST(GETDATE() AS  VARCHAR(11)) + ''' '      
 		IF(@CONDITIONQUERY != '')        
		BEGIN        
			SET @@SQLQUERY = @@SQLQUERY +' AND ' + @CONDITIONQUERY        
		END 

		SET @@SQLQUERY = @@SQLQUERY +' UNION ALL SELECT '+CAST(@TEMPLATEGROUPID AS VARCHAR(10)) +'   TemplateGroupId,NULL AS ConsiledAmount,SUM(AMOUNT) AS NonConsiledAmount,'''+ @TEMPALTEGROUPNAME +''' TemplateGroupName,'+CAST(@TEMPLATEID AS VARCHAR(10)) +'   TemplateId,'''+ @TEMPALTENAME +''' TemplateName 
		FROM PRIMARYRECONSILEDATA WHERE TemplateId in ( '+CAST(@TEMPLATEID AS VARCHAR(10)) +', '+CAST(@PRIMARYTEMPLATEID AS VARCHAR(10)) +') 
		and ID not in (select PrimaryId from  RECONSILERAWDATA WHERE ISRECONSILED =1 	AND TEMPLATEID = '+CAST(@TEMPLATEID AS VARCHAR(10)) +' And CAST(LASTUPDATE AS DATE) >= ''' + CAST(GETDATE() AS  VARCHAR(11)) + ''' )
		And CAST(LASTUPDATE AS DATE) >= ''' + CAST(GETDATE() AS  VARCHAR(11)) + ''' '      
 	--	IF(@CONDITIONQUERY != '')        
		--BEGIN        
		--	SET @@SQLQUERY = @@SQLQUERY +' AND ' + @CONDITIONQUERY        
		--END 
SET @@COUNT = @@COUNT + 1        
FETCH NEXT FROM RECONSILEREPORT_CURSOR INTO  @TEMPLATEGROUPID,@TEMPALTEGROUPNAME,@TEMPLATEID,@TEMPALTENAME,@CONDITIONQUERY,@PRIMARYTEMPLATEID             
END          
CLOSE RECONSILEREPORT_CURSOR          
DEALLOCATE RECONSILEREPORT_CURSOR  
EXEC(@@SQLQUERY)


set @@SQLQUERY =''
DECLARE @intFlag INT =0
DECLARE ADDINGBLANKROWS_CURSOR CURSOR          
LOCAL  FORWARD_ONLY  FOR          
SELECT DISTINCT TemplateGroupId,NUMBEROFBLANKROWS FROM ##TEMPREMAININGCOUNT WHERE NUMBEROFBLANKROWS <> 0
OPEN ADDINGBLANKROWS_CURSOR          
FETCH NEXT FROM ADDINGBLANKROWS_CURSOR INTO  @TEMPLATEGROUPID,@NUMBEROFBLANKROWS       
WHILE @@FETCH_STATUS = 0          
BEGIN 
SET  @intFlag = 1  
WHILE (@intFlag <=@NUMBEROFBLANKROWS)
				BEGIN
				SET @@SQLQUERY = @@SQLQUERY + 'INSERT INTO ##TEMPDASHBOARD SELECT '+CAST(@TEMPLATEGROUPID AS VARCHAR(10)) +'   TemplateGroupId,NULL AS ConsiledAmount,NULL AS NonConsiledAmount,''ZZZZZZZZBLANKROW'' TemplateGroupName,0  TemplateId,'''+CONVERT(varchar(255), NEWID()) +''' TemplateName ' 
				SET @intFlag = @intFlag + 1
				END		
FETCH NEXT FROM ADDINGBLANKROWS_CURSOR INTO  @TEMPLATEGROUPID,@NUMBEROFBLANKROWS           
END          
CLOSE ADDINGBLANKROWS_CURSOR          
DEALLOCATE ADDINGBLANKROWS_CURSOR  
exec(@@SQLQUERY) 

SELECT DB.TemplateGroupId ,ISNULL(SUM(ConsiledAmount),0) ConsiledAmount ,ISNULL(SUM(NonConsiledAmount),0) NonConsiledAmount,TemplateGroupName
 ,[TemplateId],[TemplateName],cast(DENSE_RANK () over (order by DB.TemplateGroupId desc) as int) as TemplateSpilt   FROM ##TEMPDASHBOARD  DB

GROUP BY    DB.TemplateGroupId ,TemplateGroupName ,[TemplateId],[TemplateName] 
DROP TABLE ##TEMPDASHBOARD
DROP TABLE ##TEMPREMAININGCOUNT   
END	 